config/routes.rb
Test1::Application.routes.draw do
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  match 'favorite/:handle' => 'users#favorite'
  match 'unfavorite/:handle' => 'users#unfavorite'
  
  resources :users
  resources :sessions
  resources :food_trucks, only: :index do
    get :map, on: :collection
  end
  root to: 'food_trucks#index'

end

app/models/food_truck.rb
class FoodTruck < ActiveRecord::Base
  attr_accessor :distance
  attr_accessible :name, :address, :latitude, :longitude, :handle
  has_and_belongs_to_many :fans, class_name: "User"

  def self.near(lat, long, distance_threshold)
    require 'geokit'

    here = Geokit::LatLng.new(lat, long)

    food_trucks = FoodTruck.order(:name)
    food_trucks.delete_if do |food_truck|
      food_truck.distance = here.distance_to Geokit::LatLng.new(food_truck.latitude, food_truck.longitude)
      food_truck.distance > distance_threshold
    end
    food_trucks.sort! {|x, y| x.distance.to_f <=> y.distance.to_f }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :password, :password_confirmation, :last_location
  has_and_belongs_to_many :favorites, class_name: "FoodTruck"
  
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/food_trucks_controller.rb
class FoodTrucksController < ApplicationController
  after_filter :save_last_location
  
  def map
    @food_trucks = FoodTruck.order(:name)
  end

  def index
    unless params[:location].nil?
      Geokit::Geocoders::google = "AIzaSyDjpc3N49wLGD0LtRTkwIjxrRBDx1hAaco"
      loc = GeoKit::Geocoders::GoogleGeocoder.geocode params[:location]
      @my_long, @my_lat = loc.ll.split(',')
      @food_trucks = FoodTruck.near(@my_long, @my_lat, 5)			
    else
      @food_trucks = nil
    end
  end
  
  private
  def save_last_location
    if current_user
		  current_user.last_location = params[:location]
		  current_user.save
		end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Successfully logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
  
  def favorite
    if current_user
      ft = FoodTruck.find_by_handle(params[:handle])
      if ft
        current_user.favorites << ft
        @result = true;
      else
        @result = false
      end
    else
      @result = false
    end
    render layout: false
  end
  
  def unfavorite
    if current_user
      ft = FoodTruck.find_by_handle(params[:handle])
      if ft && current_user.favorites.include?(ft)
        current_user.favorites.delete ft
        @result = true;
      else
        @result = false
      end
    else
      @result = false
    end
    render :favorite, layout: false
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_truck_helper.rb
module FoodTruckHelper
  def google_distance_query_string(food_trucks, location)
    querystring = "https://maps.googleapis.com/maps/api/distancematrix/json?sensor=false&origins=#{location}&destinations="
    
    food_trucks.each_with_index do |food_truck, index|
      querystring << (food_truck.latitude + "," + food_truck.longitude)
    	querystring << u("|") unless (index == food_trucks.count - 1)
    end
    querystring
  end
  
  def food_trucks_nearby(food_trucks, distance_threshold, location = "34.0634625,-118.3680602")
    q = google_distance_query_string(food_trucks, location)
    nearby = []
    
    require 'open-uri'
    file = open(q)
    json = ActiveSupport::JSON.decode(file.read)

    json['rows'][0]['elements'].each_with_index do |x, index|
      truck_distance = x['distance']['value']
      if truck_distance <= distance_threshold
        nearby << { distance: truck_distance, name: food_trucks[index].name }
      end
    end
    
    nearby
    
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/food_trucks/index.html.erb
<% content_for :head do %>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDjpc3N49wLGD0LtRTkwIjxrRBDx1hAaco&sensor=false"></script>

<script type="text/javascript">

var map;
var infowindow = null;
var mycoords;

function stripslashes(str)
{
	str=str.replace(/\\'/g,'\'');
	str=str.replace(/\\"/g,'"');
	return str;
}

$(function() {
	$('#my_location').click(function() {
		var mycoords;
		if (navigator.geolocation)
		{
			navigator.geolocation.getCurrentPosition(function(position)
			{
				console.log("here");
		  	var lat = position.coords.latitude;
		    var lng = position.coords.longitude;
				$('#location').val(lat + ',' + lng);
				$("#loc_form").submit();
			}, function(err) {
				if (err.code == 1)
					console.log("How are you gonna expect this to work if you deny me?")
			});
		} else {
			console.log("Geolocation not supported.");
		}
		
		return false;
	});
	
	<% unless @food_trucks.nil? %>
	
	function initialize() 
	{
		mycoords = new google.maps.LatLng(<%= @my_long %>, <%= @my_lat %>);
				
		var mapStyle = [
	  	{
	 	   featureType: "landscape",
		    stylers: [
		      { saturation: 65 },
		      { hue: "#ffe500" },
		      { lightness: 33 }
		    ]
		  },{
		    featureType: "landscape",
		    stylers: [
		      { hue: "#ccff00" }
		    ]
		  },{
		    featureType: "poi.park",
		    stylers: [
		      { hue: "#ccff00" }
		    ]
		  },{
		    featureType: "road",
		    stylers: [
		      { saturation: -65 },
		      { hue: "#ffc300" },
		      { lightness: 5 }
		    ]
		  },{
		    featureType: "water",
		    stylers: [
		      { gamma: 1.02 },
		      { saturation: 31 },
		      { lightness: 2 },
		      { hue: "#ffa200" }
		    ]
		  },{
		  },{
		    featureType: "poi.business",
		    stylers: [
		      { hue: "#ff9900" },
		      { saturation: 44 }
		    ]
		  },{
		  },{
		    featureType: "water",
		    stylers: [
		      { lightness: 45 },
		      { saturation: -60 },
		      { hue: "#1aff00" }
		    ]
		  },{
		  }
		];

		var mapStyleType = new google.maps.StyledMapType(mapStyle, {name: "Old School"})

	  var myOptions = {
	    zoom: 12,
	    center: mycoords,
	    mapTypeControlOptions: {
				mapTypeIds: [google.maps.MapTypeId.ROADMAP, 'old_school']
	 		},
			streetViewControl: false,
			zoomControl: false,
			panControl: false,
			mapTypeControl: false,
			backgroundColor: "#fbfdf1"
	  };
	
		map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
	  setMarkers(map, foodtrucks);
		map.mapTypes.set('old_school', mapStyleType);
		map.setMapTypeId('old_school')
	  infowindow = new google.maps.InfoWindow({
	    content: "placeholder",
			pixelOffset: new google.maps.Size(0, -34)
	  });
	
		var customimg = new google.maps.MarkerImage('/assets/marker_sprite.png', new google.maps.Size(21, 34), new google.maps.Point(0, 0));
		var customshadow = new google.maps.MarkerImage('/assets/marker_sprite.png', new google.maps.Size(28, 34), new google.maps.Point(28, 0), new google.maps.Point(0, 34));
		
		var m = new google.maps.Marker({
      position: mycoords,
      map: map,
      title: "ME!",
      zIndex: 9999,
			icon: customimg,
			shadow: customshadow
    });
	}
		
	var foodtrucks = [
		<% @food_trucks.each_with_index do |food_truck, index| %>
		  ['<%= escape_javascript food_truck.name %>', <%= food_truck.latitude %>, <%= food_truck.longitude %>, <%= index+1 %>, <%= food_truck.fans.count %>]
		  <% if ((index+1) < @food_trucks.length) %>
		      ,
		  <% end %>  
		<% end %>
  ];
	
  function setMarkers(map, locations)
  {
    for (var i = 0; i < locations.length; i++)
    {
      var truck = locations[i];
      var myLatLng = new google.maps.LatLng(truck[1], truck[2]);
      var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: truck[0],
        zIndex: truck[3],
				fans: truck[4]
      });
  
      google.maps.event.addListener(marker, 'click', function() {
        infowindow.setContent(this.title + " has " + this.fans + " fan(s)");
				infowindow.setOptions({pixelOffset: new google.maps.Size(0, 0)});
        infowindow.open(map, this);
      });
    }
	}
	
	$(initialize);
	<% end %>
});

function recentermap(lng, lat, name)
{
	var point = new google.maps.LatLng(lat, lng)
	
	map.setZoom(13);
	map.panTo(point);
	
	infowindow.setPosition(point);
	name = stripslashes(name);
	infowindow.setContent(unescape(name));
	infowindow.setOptions({pixelOffset: new google.maps.Size(0, -34)});
	infowindow.open(map);
}

$(function() {
	$('#nearby_foodtrucks').mouseleave(function() {
		map.setZoom(12);
		map.setCenter(mycoords);
		infowindow.close();
	});
	$('#nearby_foodtrucks li').mouseenter(function() {
		var l = $(this)
		recentermap(l.attr("data-lng"), l.attr("data-lat"), l.attr("title"));
	});
	$('.heart').click(function() {
		
		<% if !current_user %>
		
		$('#createaccount').show();
		
		<% else  %>
		jQuery.ajax($(this).attr("href"));
		console.log($(this).attr("href").indexOf("/favorite/"))
		$(this).attr("href").indexOf("/favorite/") == 0? $(this).attr("href", $(this).attr("href").replace("/favorite/", "/unfavorite/")) : $(this).attr("href", $(this).attr("href").replace("/unfavorite/", "/favorite/"));
		
		<% end  %>
		
		$(this).toggleClass('favorite');
		
		return false;
	});
});

</script>
<% end %>

<div id="left" <% if @food_trucks.nil? then %> class="full" <% end %> >
	<form id="loc_form" method="get" action="/">
		<p>use: <a href="#" id="my_location">current location</a>
		<% if current_user && current_user.last_location %>
			| <a href="?location=<%= current_user.last_location %>">last location (<%= current_user.last_location %>)</a>
		<% end %>
		</p>
		<input id='location' type='ssearch' placeholder='where?' value="<%= params[:location] %>" name='location'/> <input type="submit" value="Search">
	</form>

	<% unless @food_trucks.nil? %>
		<h3>Food Trucks Within 5 Miles</h3>
		<p id="createaccount">Your favorite food trucks will not be saved. <%= link_to "Create an account", signup_path %> to start trucking!</p>
		<ul id="nearby_foodtrucks">
		<% @food_trucks.sort_by! {|f| f.distance}.each do |food_truck| %>
  		<li data-lng="<%= food_truck.longitude %>" data-lat="<%= food_truck.latitude %>" title="<%= escape_javascript food_truck.name %>">
			<% if current_user && current_user.favorites.include?(food_truck) then heart_class = "favorite" end %>
				<a href="/<%= heart_class == "favorite" ? "un" : "" %>favorite/<%= food_truck.handle %>" class="heart <%= heart_class %>"><img src="/assets/red_heart.png"/></a><%= food_truck.name %><br />(<a href="http://twitter.com/<%= food_truck.handle %>">@<%= food_truck.handle %></a>) - <%= number_with_precision(food_truck.distance, {precision: 2} ) %> miles</li>
	<% end %>
		</ul>
	<% end %>
</div>

<% unless @food_trucks.nil? %>
<div id="map_canvas"></div>
<% end %>

app/views/food_trucks/index.html.slim
#left
  = form_tag food_trucks_path, method: 'get' do
    = label_tag :location
    = text_field_tag :location 
    = submit_tag 'search' 

  - if @food_trucks
    ol#food-trucks
      - @food_trucks.each do |food_truck|
        li data-lng="#{food_truck.longitude}" data-lat="#{food_truck.latitude}" title="#{food_truck.name}"
          = food_truck.name
          br
          | (
          span.distance = number_with_precision food_truck.distance, precision: 2
          |  miles away)


#map_canvas

script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCxQkZ5bIQf0KZFxQO85S9QSe870F66pB8&sensor=false"

javascript:
  var user_lat = #{@my_lat};
  var user_long = #{@my_long};
  var food_truck_markers = #{{@food_trucks.to_json}};

coffee:
  $ ->
    infowindow = new google.maps.InfoWindow

    # print the map
    if user_lat && user_long
      mycoords = new google.maps.LatLng user_long, user_lat
    else
      mycoords = new google.maps.LatLng 34.0636014, -118.3682263
    mapOptions =
      zoom: 12
      center: mycoords
      mapTypeId: google.maps.MapTypeId.ROADMAP
    map = new google.maps.Map document.getElementById('map_canvas'), mapOptions
    # set the marker of user location
    customimg = new google.maps.MarkerImage '/assets/marker_sprite.png', new google.maps.Size(21, 34), new google.maps.Point(0, 0)
    customshadow = new google.maps.MarkerImage '/assets/marker_sprite.png', new google.maps.Size(28, 34), new google.maps.Point(28, 0), new google.maps.Point(0, 34)

    mymarker = new google.maps.Marker position:mycoords, map:map, title:"I'm here!", icon: customimg, shadow: customshadow
    onclick = ->
      infowindow.setContent("I'M HERE!")
      infowindow.open(map, mymarker) 
    google.maps.event.addListener mymarker, 'click', onclick

    # set the marker of nearby foodtrucks
    for food_truck in food_truck_markers
      do (food_truck) ->
        console.log(food_truck.longitude)
        myLatLng = new google.maps.LatLng food_truck.latitude, food_truck.longitude
        truck_marker = new google.maps.Marker position: myLatLng, map: map, title: food_truck.name
        onclick = ->
          infowindow.setContent(food_truck.name)
          infowindow.open(map, truck_marker) 
        google.maps.event.addListener truck_marker, 'click', onclick

    # recenter when user click the order list
    stripslashes = (str) ->
      str = str.replace(/\\'/g, "'")
      str = str.replace(/\\"/g, "\"")
      str
    recentermap = (lng, lat, name) ->
      point = new google.maps.LatLng(lat, lng)
      map.setZoom 13
      map.panTo point
      infowindow.setPosition point
      name = stripslashes(name)
      infowindow.setContent unescape(name)
      infowindow.setOptions pixelOffset: new google.maps.Size(0, -34)
      infowindow.open(map)

    $("#food-trucks").mouseleave ->
      map.setZoom 12
      map.setCenter mycoords
      infowindow.close()

    $("#food-trucks li").mouseenter ->
      l = $(this)
      recentermap l.attr("data-lng"), l.attr("data-lat"), l.attr("title")

app/views/food_trucks/map.html.erb
<% content_for :head do %>
	<link href="http://google-developers.appspot.com/maps/documentation/javascript/examples/default.css" rel="stylesheet" type="text/css" />
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDjpc3N49wLGD0LtRTkwIjxrRBDx1hAaco&sensor=false"></script>
  <script type="text/javascript">

		function initialize() 
		{
		  var myLatlng = new google.maps.LatLng(34.0522,-118.2428);
						
			var mapStyle = [
			  {
			    featureType: "landscape",
			    stylers: [
			      { saturation: 65 },
			      { hue: "#ffe500" },
			      { lightness: 33 }
			    ]
			  },{
			    featureType: "landscape",
			    stylers: [
			      { hue: "#ccff00" }
			    ]
			  },{
			    featureType: "poi.park",
			    stylers: [
			      { hue: "#ffdd00" }
			    ]
			  },{
			    featureType: "road",
			    stylers: [
			      { saturation: -65 },
			      { hue: "#ffc300" },
			      { lightness: 5 }
			    ]
			  },{
			    featureType: "water",
			    stylers: [
			      { gamma: 1.02 },
			      { saturation: 31 },
			      { lightness: 2 },
			      { hue: "#ffa200" }
			    ]
			  },{
			  },{
			    featureType: "poi.business",
			    stylers: [
			      { hue: "#ff9900" },
			      { saturation: 44 }
			    ]
			  },{
			  },{
			    featureType: "water",
			    stylers: [
			      { lightness: 45 },
			      { saturation: -60 },
			      { hue: "#1aff00" }
			    ]
			  },{
			  }
			];
	
			var mapStyleType = new google.maps.StyledMapType(mapStyle, {name: "Old School"})

		  var myOptions = {
		    zoom: 10,
		    center: myLatlng,
		    mapTypeControlOptions: {
					mapTypeIds: [google.maps.MapTypeId.ROADMAP, 'old_school']
		 		},
		  };
  
    	var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
		  setMarkers(map, foodtrucks);
			map.mapTypes.set('old_school', mapStyleType);
			map.setMapTypeId('old_school')
	    infowindow = new google.maps.InfoWindow({
	      content: "placeholder"
	    });
	
			var mycoords;
			if (navigator.geolocation)
			{
				navigator.geolocation.getCurrentPosition(function(position)
				{
	      	var latitude = position.coords.latitude;
	        var longitude = position.coords.longitude;
	        mycoords = new google.maps.LatLng(latitude, longitude);
					console.log(mycoords);

					var customimg = new google.maps.MarkerImage('/assets/marker_sprite.png', new google.maps.Size(21, 34), new google.maps.Point(0, 0));
					var customshadow = new google.maps.MarkerImage('/assets/marker_sprite.png', new google.maps.Size(28, 34), new google.maps.Point(28, 0), new google.maps.Point(0, 34));
					
					var m = new google.maps.Marker({
		        position: mycoords,
		        map: map,
		        title: "ME!",
		        zIndex: 9999,
						icon: customimg,
						shadow: customshadow
		      });
		
					google.maps.event.addListener(m, 'click', function() {
		        infowindow.setContent(this.title);
		        infowindow.open(map, this);
		      });
					
				});
			} else {
        console.log("Geolocation API is not supported in your browser.");
			}
	
	  }

		  var foodtrucks = [
				<% @food_trucks.each_with_index do |food_truck, index| %>
				  ['<%= escape_javascript food_truck.name %>', <%= food_truck.latitude %>, <%= food_truck.longitude %>, <%= index+1 %>]
				  <% if ((index+1) < @food_trucks.length) %>
				      ,
				  <% end %>  
				<% end %>
		  ];

		  var infowindow = null;
		  function setMarkers(map, locations)
		  {
		    for (var i = 0; i < locations.length; i++)
		    {
		      var truck = locations[i];
		      var myLatLng = new google.maps.LatLng(truck[1], truck[2]);
		      var marker = new google.maps.Marker({
		        position: myLatLng,
		        map: map,
		        title: truck[0],
		        zIndex: truck[3],
		      });
      
		      google.maps.event.addListener(marker, 'click', function() {
		        infowindow.setContent(this.title);
		        infowindow.open(map, this);
		      });
		    }
		  }
			$(initialize);
	</script>
<% end %>

<div id="map_canvas" style="width:800px; height: 600px;"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	  <title>Nearest Food Trucks</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
		<%= content_for :head %>
	</head>
	<body>
		<div id="content">
			<div id="user_info">
				<% if current_user %>
					Logged in as <span class="username"><%= current_user.email %></span> | <%= link_to "Log Out", logout_path %>
				<% else %>
					<%= link_to "Sign Up", signup_path %> or 
					<%= link_to "Log In", login_path %>
				<% end %>
			</div>
			<header style='text-align: center;'>
				<a href="/"><img src='/assets/foodtrucks.png' /></a>
			</header>
			<% flash.each do |name, msg| %>
				<%= content_tag :div, msg, id: "flash_#{name}" %>
			<% end %>
			<%= yield %>
		</div>
	</body>
</html>

app/views/users/favorite.html.erb
<%= @result %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>